<?php

namespace Unit;

use Codeception\Test\Unit;
use JetBrains\PhpStorm\NoReturn;
use StrannyiTip\PhpTypes\Http\File;


class FileTest extends Unit
{
    protected function _before(): void
    {
        touch(__DIR__ . '/data/file_for_remove.txt');
        touch(__DIR__ . '/data/file_for_test_move.txt');

        parent::_before(); // TODO: Change the autogenerated stub
    }

    protected function _after(): void
    {
        @unlink(__DIR__ . '/data/file_for_remove.txt');

        parent::_after(); // TODO: Change the autogenerated stub
    }

    #[NoReturn]
    public function testMime()
    {
        $file = new File(__DIR__ . '/data/example.txt');
        $this->assertEquals('text/plain', $file->mimeType(), "test for check mime type");
    }

    public function testSize()
    {
        $file = new File(__DIR__ . '/data/example.txt');
        $this->assertEquals(17, $file->size(), 'Test for check size');
    }

    public function testExists()
    {
        $existed_file = new File(__DIR__ . '/data/example.txt');
        $unexisted_file = new File(__DIR__ . 'some_file');
        $this->assertTrue($existed_file->exists(), 'Test for check for existed file is exist');
        $this->assertFalse($unexisted_file->exists(), 'Test for check for unexisted file is not exist');
    }

    public function testHash()
    {
        $file = new File(__DIR__ . '/data/example.txt');
        $this->assertEquals('3eb0ca2cc77c85315873108cc019763d47c3061a2d3ed9c1db3f8eb02e4e3863', $file->hash(), 'Check hash with default algorithm');
        $this->assertEquals('5071d19fa700b9c0a48188507a2a2682', $file->hash('md5'), 'Check hash with setted algorithm (md5)');
    }

    public function testExt()
    {
        $file = new File(__DIR__ . '/data/example.txt');
        $this->assertEquals('txt', $file->ext(), 'Test for get correct extension');
    }

    public function testRemove()
    {
        $file = new File(__DIR__ . '/data/file_for_remove.txt');
        $this->assertTrue($file->exists(), 'Check for file exists before removing');
        $file->remove();
        $this->assertFalse($file->exists(), 'Check for file not exists after removing');
    }

    public function testMove()
    {
        $file = new File(__DIR__ . '/data/file_for_test_move.txt');
        $moved_filename = $file->move(__DIR__ . '/data');
        $moved_file = new File($moved_filename);
        $this->assertTrue($moved_file->exists(), 'Test for check what file moved correctly');
        $moved_file->remove();
    }
}
